name: Secret Scanning (gitleaks)

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    env:
      GITLEAKS_SARIF_OUTPUT: gitleaks.sarif

    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install gitleaks
        run: bash ci/setup-tools.sh --install-tool gitleaks

      - name: Install and run gitleaks
        run: >
          gitleaks dir .
          --config ci/suppress_gitleaks.toml
          --redact
          --report-format sarif
          --report-path "$GITLEAKS_SARIF_OUTPUT"

      - name: Upload SARIF to code scanning
        if: always()
        uses: github/codeql-action/upload-sarif@5584cec5894a031d9021665d6df20e6c38e7a266 #v2.25.6
        with:
          sarif_file: ${{ env.GITLEAKS_SARIF_OUTPUT }}
          category: gitleaks
